[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "aiphase9"
version = "0.1.0"
description = "Running Local Models"
requires-python = ">=3.10"
dependencies = [
    "safetensors"
]

[project.optional-dependencies]
dev = ["black", "ruff", "pytest"]

[tool.setuptools.packages.find]
where = ["src"]
